language: php

php:
  - 5.5
  - 5.4
  - 5.3

env:
  matrix:
    - TEST_SUITE=CoreTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL

script: ./travis.sh

install:
  - mkdir AdvancedCampaignReporting
  - cp -R !(AdvancedCampaignReporting) AdvancedCampaignReporting
  - git clone https://github.com/piwik/piwik.git piwik
  - cd piwik
  - git checkout master
  - git submodule init
  - git submodule update || true
  - composer install
  - rm -rf plugins/AdvancedCampaignReporting
  - cd ../
  - mv AdvancedCampaignReporting piwik/plugins

before_script:
  - cd piwik
  - uname -a
  - date
  - mysql -e 'create database piwik_tests;'
  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - wget https://raw.github.com/piwik/piwik-tests-plugins/master/activateplugin.php
  - php activateplugin.php AdvancedCampaignReporting
  - cd tests/PHPUnit

after_script:
  - cat /var/log/nginx/error.log
